// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-YoYjhY7m4AddpI6UpAgDv1uQHy8dfAQ',
    appId: '1:708826960721:web:388c410a1509acf9963970',
    messagingSenderId: '708826960721',
    projectId: 'highland-62941',
    authDomain: 'highland-62941.firebaseapp.com',
    storageBucket: 'highland-62941.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXIsKSWqqkr-wAL-tGVvr1sq0Vm8_Zkx0',
    appId: '1:708826960721:android:4aaaa0f1e02526b3963970',
    messagingSenderId: '708826960721',
    projectId: 'highland-62941',
    storageBucket: 'highland-62941.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFcJOwx_Xvq_ENVO_L4vqQIEByEYJunyU',
    appId: '1:708826960721:ios:e8645417f3d0a290963970',
    messagingSenderId: '708826960721',
    projectId: 'highland-62941',
    storageBucket: 'highland-62941.appspot.com',
    iosBundleId: 'com.example.tracelyClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFcJOwx_Xvq_ENVO_L4vqQIEByEYJunyU',
    appId: '1:708826960721:ios:e8645417f3d0a290963970',
    messagingSenderId: '708826960721',
    projectId: 'highland-62941',
    storageBucket: 'highland-62941.appspot.com',
    iosBundleId: 'com.example.tracelyClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTl_RVlrkkmObn8_LMTqpKeWPrqR0WGsQ',
    appId: '1:708826960721:web:14fd244d64125308963970',
    messagingSenderId: '708826960721',
    projectId: 'highland-62941',
    authDomain: 'highland-62941.firebaseapp.com',
    storageBucket: 'highland-62941.appspot.com',
  );
}
